//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chakwal.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLocation
    {
        public CompanyLocation()
        {
            this.StockInProducts = new HashSet<StockInProduct>();
            this.StockInProducts1 = new HashSet<StockInProduct>();
            this.StockInItems = new HashSet<StockInItem>();
            this.StockOuts = new HashSet<StockOut>();
            this.StockOuts1 = new HashSet<StockOut>();
            this.Users = new HashSet<User>();
        }
    
        public int LocationId { get; set; }
        public int CompanyId { get; set; }
        public string LocationName { get; set; }
        public string LocationAddress { get; set; }
        public bool MainLocation { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual ICollection<StockInProduct> StockInProducts { get; set; }
        public virtual ICollection<StockInProduct> StockInProducts1 { get; set; }
        public virtual ICollection<StockInItem> StockInItems { get; set; }
        public virtual ICollection<StockOut> StockOuts { get; set; }
        public virtual ICollection<StockOut> StockOuts1 { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
