//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chakwal.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Production
    {
        public Production()
        {
            this.ItemUseds = new HashSet<ItemUsed>();
            this.ProductMades = new HashSet<ProductMade>();
        }
    
        public long ProductionId { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public Nullable<int> TeamId { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual ICollection<ItemUsed> ItemUseds { get; set; }
        public virtual Team Team { get; set; }
        public virtual ICollection<ProductMade> ProductMades { get; set; }
    }
}
