//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chakwal.Data.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOut
    {
        public long StockOutId { get; set; }
        public int ProductId { get; set; }
        public System.DateTime DateOut { get; set; }
        public int StockOutLocation { get; set; }
        public Nullable<int> LocationTo { get; set; }
        public decimal Quantity { get; set; }
        public decimal SoldUnitPrice { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual CompanyLocation CompanyLocation { get; set; }
        public virtual CompanyLocation CompanyLocation1 { get; set; }
        public virtual Product Product { get; set; }
    }
}
